{$DEFINE PEAKTOP:IDE/$COMMON/LIBRARYUPDATES_LANG.INC}
  //================= PEAKTOP:IDE/$COMMON/LIBRARYUPDATES_LANG.INC ==============
const
  mgs_library_updates_caption     = 'Обновление библиотеки кода';
  mgs_library_updates_revision    = 'текущая версия';
  mgs_library_updates_svn_check   = 'проверка текущей версии стандартной библиотеки кода';
  mgs_library_updates_svn_cleanup = 'очистка кэша';
  mgs_library_updates_svn_update  = 'обновление стандартной библиотеки кода';    
